<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-07935JK" failures="2" tests="10" name="Test" time="10.796" errors="0" timestamp="2024-08-17T17:07:38 IST">
  <testcase classname="restAssured.RestAssured" name="testing" time="0.009"/>
  <testcase classname="restAssuredDemo.Rest" name="restCheck" time="2.194"/>
  <testcase classname="restAssuredDemo.Rest" name="GetJsonArrayData" time="0.355"/>
  <testcase classname="restAssuredDemo.Rest" name="PostMethod" time="0.817"/>
  <testcase classname="restAssuredDemo.Rest" name="DeleteMethod" time="0.623"/>
  <testcase classname="restAssuredDemo.Rest" name="PutMethod" time="0.676"/>
  <testcase classname="restAssured.RestAuthentication" name="restBasicAuthentication" time="2.538"/>
  <testcase classname="restAssured.RestAuthentication" name="bearerTokenAuth" time="0.639">
    <failure type="java.lang.AssertionError" message="Request failed expected [401] but found [200]">
      <![CDATA[java.lang.AssertionError: Request failed expected [401] but found [200]
at restAssured.RestAuthentication.bearerTokenAuth(RestAuthentication.java:54)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- bearerTokenAuth -->
  <testcase classname="restAssured.RestAuthentication" name="OAuth2" time="0.512">
    <failure type="java.lang.AssertionError" message="Request failed expected [401] but found [200]">
      <![CDATA[java.lang.AssertionError: Request failed expected [401] but found [200]
at restAssured.RestAuthentication.OAuth2(RestAuthentication.java:84)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- OAuth2 -->
  <testcase classname="restAssured.RestAuthentication" name="restBasicAuthenticationWithGivenWhen" time="2.363"/>
</testsuite> <!-- Test -->
