<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="10" passed="8" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-08-17T17:07:27 IST" name="Suite" finished-at="2024-08-17T17:07:38 IST" duration-ms="10796">
    <groups>
    </groups>
    <test started-at="2024-08-17T17:07:27 IST" name="Test" finished-at="2024-08-17T17:07:38 IST" duration-ms="10796">
      <class name="restAssured.RestAssured">
        <test-method signature="testing()[pri:0, instance:restAssured.RestAssured@6c64cb25]" started-at="2024-08-17T17:07:27 IST" name="testing" finished-at="2024-08-17T17:07:27 IST" duration-ms="9" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testing -->
      </class> <!-- restAssured.RestAssured -->
      <class name="restAssuredDemo.Rest">
        <test-method signature="restCheck()[pri:0, instance:restAssuredDemo.Rest@72d1ad2e]" started-at="2024-08-17T17:07:27 IST" name="restCheck" finished-at="2024-08-17T17:07:30 IST" duration-ms="2194" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- restCheck -->
        <test-method signature="GetJsonArrayData()[pri:1, instance:restAssuredDemo.Rest@72d1ad2e]" started-at="2024-08-17T17:07:30 IST" name="GetJsonArrayData" finished-at="2024-08-17T17:07:30 IST" duration-ms="355" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GetJsonArrayData -->
        <test-method signature="PostMethod()[pri:2, instance:restAssuredDemo.Rest@72d1ad2e]" started-at="2024-08-17T17:07:30 IST" name="PostMethod" finished-at="2024-08-17T17:07:31 IST" duration-ms="817" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PostMethod -->
        <test-method signature="DeleteMethod()[pri:3, instance:restAssuredDemo.Rest@72d1ad2e]" started-at="2024-08-17T17:07:31 IST" name="DeleteMethod" finished-at="2024-08-17T17:07:31 IST" duration-ms="623" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DeleteMethod -->
        <test-method signature="PutMethod()[pri:4, instance:restAssuredDemo.Rest@72d1ad2e]" started-at="2024-08-17T17:07:31 IST" name="PutMethod" finished-at="2024-08-17T17:07:32 IST" duration-ms="676" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PutMethod -->
      </class> <!-- restAssuredDemo.Rest -->
      <class name="restAssured.RestAuthentication">
        <test-method signature="restBasicAuthentication()[pri:0, instance:restAssured.RestAuthentication@2d7275fc]" started-at="2024-08-17T17:07:32 IST" name="restBasicAuthentication" finished-at="2024-08-17T17:07:35 IST" duration-ms="2538" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- restBasicAuthentication -->
        <test-method signature="bearerTokenAuth()[pri:2, instance:restAssured.RestAuthentication@2d7275fc]" started-at="2024-08-17T17:07:35 IST" name="bearerTokenAuth" finished-at="2024-08-17T17:07:35 IST" duration-ms="639" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Request failed expected [401] but found [200]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Request failed expected [401] but found [200]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at restAssured.RestAuthentication.bearerTokenAuth(RestAuthentication.java:54)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bearerTokenAuth -->
        <test-method signature="OAuth2()[pri:3, instance:restAssured.RestAuthentication@2d7275fc]" started-at="2024-08-17T17:07:35 IST" name="OAuth2" finished-at="2024-08-17T17:07:36 IST" duration-ms="512" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Request failed expected [401] but found [200]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Request failed expected [401] but found [200]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at restAssured.RestAuthentication.OAuth2(RestAuthentication.java:84)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OAuth2 -->
        <test-method signature="restBasicAuthenticationWithGivenWhen()[pri:4, instance:restAssured.RestAuthentication@2d7275fc]" started-at="2024-08-17T17:07:36 IST" name="restBasicAuthenticationWithGivenWhen" finished-at="2024-08-17T17:07:38 IST" duration-ms="2363" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- restBasicAuthenticationWithGivenWhen -->
      </class> <!-- restAssured.RestAuthentication -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
